### PR TITLE
Tfssupport

### PR DESCRIPTION
**Pull request by dapngn**
This will add TFS support to warmup.
- It leverages the TeamFoundation namespace installed via 2 Nuget packages
- Set the TFS server in the app.config
- On the command line give the fully qualified server address of the template, as you would from the '$' token
- It creates a temporary workspace, does a get latest, checks out the files, project wide un-binding, then deletes the temporary workspace

The regular warmup flow takes care of the rest.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Thanks - we will take a look and evaluate this over the next month or two.

**Comment by dapngn** [comment]
Feel free to close this request.  It would be a better fit in a plug-in architecture, rather than in the core code.  There is a dependency on a couple of TFS libs, which come installed in VS2012, but are not available prior to that.  Also, TFS is just not as flexible as the other SCM options, so that leads to some weird workarounds.  Basically you can't just call the tool from within an existing workspace, because TFS doesn't support nested workspaces (that I am aware of), which leads to project generation, followed by moving it into the destination workspace.  It was cool to get it working with TFS, but in the end, leaving it as a fork is fine.

**Comment by ferventcoder** [comment]
@RussMartinez That's fine. Keep in mind that this was still on the list to evaluate. If you were closing the PR just due to the above, then we are fine with that. If it was also because we are slow to evaluate, I'd urge you to keep it open. We will eventually get to it.

**Comment by dapngn** [comment]
@ferventcoder no worries.  I have been mulling over a better implementation, testing, etc...

**Pull request closed without merging**
