### PR TITLE
Custom replacing tokens

### PR DESCRIPTION
**Pull request by topas**
I think more tokens for replacing in files will be useful. For example I am using `__COMPANYNAME__` token for replacing company name in file headers. Custom tokens can be configured in the section of app.config.

### CODE REVIEW

**Comment by ferventcoder** [comment]
This looks pretty good. Looking at some of the commits though, they are repointing items to your git repo instead of chucknorris (even though they may be pointed at drusellers right now).

**Comment by ferventcoder** [comment]
Sorry this has taken so long to review. This summer was about prioritization.

**Comment by drusellers** [comment]
topas, sorry - I am awake now. If you want to rebase this on top of the current master - I will take a look at merging this in.

**Comment by topas** [comment]
Hi, I made my changes based on current version. Can you check it, please?

**Comment by drusellers** [comment]
done

**Comment by ferventcoder** [comment]
Hey fellers - kind of naive but https://github.com/chucknorris/warmup/issues/5

**Pull request merged**
